Update overview documentation
MicrosoftDocs/microsoft-authentication-library-for-python pull request #63
Opened 2024-02-29 16:27 UTC by SHERMANOUKO

2024-03-01 10:55 UTC, SHERMANOUKO commented
@Dickson-Mwendia please review.

2024-03-06 13:42 UTC, Dickson-Mwendia requested changes
@SHERMANOUKO great work here on improving the overview, I like it. Left a couple of minor suggestions but overall, it looks good.

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +- Samples from the [library repository](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.22.0/sample/interactive_sample.py).
```suggestion
- Samples from the [library repository](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.22.0/sample). These samples demonstrate the different configurations and auth flows that you implement using MSAL Python.
```

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +- Samples from the [library repository](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/1.22.0/sample/interactive_sample.py).
Let's point to the samples directory here, rather than the first code sample.

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +TRhere are several samples you can use to get started with MSAL Python.
```suggestion
There are several samples you can use to get started with MSAL Python.
```

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +TRhere are several samples you can use to get started with MSAL Python.
minor typo here

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +The Microsoft Authentication Library (MSAL) for Python library enables you to sign in users or apps with Microsoft identities. These identities include work and school accounts, personal microsoft ac
```suggestion
The Microsoft Authentication Library (MSAL) for Python library enables you to sign in users or apps with Microsoft identities. These identities include work and school accounts, personal Microsoft accounts, social accounts, customer accounts, and so on. Using MSAL Python, you can acquire tokens from Microsoft Entra to call protected web APIs such as [Microsoft Graph](https://graph.microsoft.io/), other Microsoft APIs, or your own APIs. MSAL Python supports various application types, including public client applications (desktop and mobile) and confidential client applications (web apps, web APIs, and daemon applications).
```

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +1. If there is no suitable token in the cache or you've chosen to skip the previous step, send a request to Microsoft Entra ID to get a token. There are different methods based on your client type an
```suggestion
1. If there's no suitable token in the cache or you chose to skip the previous step, send a request to Microsoft Entra ID to get a token. There are different methods based on your client type and scenario, but for the purposes of the example we're showing how to use [`acquire_token_interactive`](xref:msal.application.PublicClientApplication.acquire_token_interactive), which prompts the user to provide their credentials.
```

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +MSAL Python can be used by applications to acquire tokens to access protected APIs. Tokens can be acquired by different application types. These app types include desktop applications, web applicatio
```suggestion
Applications can use MSAL Python to acquire tokens for accessing protected APIs. Different app types acquire tokens using different auth flows. The supported app types include desktop applications, web applications, web APIs, and applications running on devices that don't have a browser (such as IoT devices). 
```

2024-03-06 13:42 UTC, Dickson-Mwendia commented on msal-python-conceptual/index.md
> +MSAL Python can be used by applications to acquire tokens to access protected APIs. Tokens can be acquired by different application types. These app types include desktop applications, web applicatio
Not sure if this bit sounds any better, but the idea is to eliminate the passive voice in two consecutive sentences.

2024-03-18 05:47 UTC, SHERMANOUKO commented
@Dickson-Mwendia kindly merge

2024-03-18 07:15 UTC, Dickson-Mwendia approved these changes

2024-03-18 07:15 UTC, merged